services:
  webserver:
    build: .
    ports:
      - "8000:80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SITE_URL: ${SITE_URL}
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./db/db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
