# compose.override.yaml
services:
  webserver:
    volumes:
      - ./public:/var/www/html/public
      - ./app:/var/www/html/app
      - ./core:/var/www/html/core
      - ./config:/var/www/html/config
