# compose.yaml
services:
  webserver:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SITE_URL: ${SITE_URL}
    depends_on:
      - db
    ports:
      - "8000:80"
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - backend
    volumes:
      - ./db/db-init:/docker-entrypoint-initdb.d

networks:
  backend:
